title: Weasley Clock
logo: /assets/img/clock.jpg
description: Short description of my implementation of the magical Weasley clock  from the Harry Potter books.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
